name: Build APK
on: [workflow_dispatch, push]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ANDROID_HOME: ${{ github.workspace }}/android-sdk
      ANDROID_SDK_ROOT: ${{ github.workspace }}/android-sdk

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      # Android SDK handmatig installeren (één pad, geen conflicts)
      - name: Install Android SDK (cmdline-tools)
        run: |
          set -e
          mkdir -p "$ANDROID_HOME/cmdline-tools"
          cd "$ANDROID_HOME/cmdline-tools"
          curl -L -o cmdline-tools.zip https://dl.google.com/android/repository/commandlinetools-linux-12266719_latest.zip
          unzip -q cmdline-tools.zip
          mv cmdline-tools latest
          echo "$ANDROID_HOME/cmdline-tools/latest/bin" >> $GITHUB_PATH
          echo "$ANDROID_HOME/platform-tools" >> $GITHUB_PATH

      - name: Accept SDK licenses
        run: yes | sdkmanager --licenses

      - name: Install platform + build-tools
        run: |
          sdkmanager "platform-tools" "platforms;android-34" "build-tools;34.0.0"
          sdkmanager --list | head -n 30

      # We gebruiken losse Gradle i.p.v. wrapper
      - name: Install Gradle 8.2
        run: |
          wget -q https://services.gradle.org/distributions/gradle-8.2-bin.zip
          unzip -q gradle-8.2-bin.zip
          echo "$PWD/gradle-8.2/bin" >> $GITHUB_PATH

      # Laat Gradle expliciet dit SDK-pad gebruiken
      - name: Set local.properties
        run: |
          echo "sdk.dir=$ANDROID_HOME" > local.properties

      - name: Build debug APK
        run: gradle assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: FocusFlow-debug-apk
          path: app/build/outputs/apk/debug/*.apk
